language: ruby

# https://github.com/travis-ci/travis-ci/issues/5239
before_install:
  - gem install bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.5
  - ruby-head

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails4.0.gemfile

  allow_failures:
    - rvm: ruby-head

cache: bundler
sudo: false
